# Dependabot configuration file
# See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Allow both direct and indirect updates
    open-pull-requests-limit: 5
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Commit message preferences
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    # Only allow security updates for major versions
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Docker (dev container)
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "docker"